import { Drug } from "./app/shared/models/Drug";

export const sample_drugs: Drug[] = [
    {
        id:'1',
        name: 'Antimentil',
        dosage: '1-2',
        price: 10,
        favorite: false,
        origins: 'Tilman',
        stars: 4.5,
        imageUrl: 'assets/1.jpg',
        tags: ['Stomach', 'Digest', 'Vomit'],
      },
      {
        id:'2',
        name: 'Aquilea Enrelax',
        price: 20,
        dosage: '2-3',
        favorite: true,
        origins: 'Uriach',
        stars: 4.7,
        imageUrl: 'assets/2.jpg',
        tags: ['Sleep', 'Relax'],
      },
      {
        id:'3',
        name: 'Aquilea Sueno Compact',
        price: 5,
        dosage: '1-3',
        favorite: false,
        origins: 'Uriach',
        stars: 3.5,
        imageUrl: 'assets/3.jpg',
        tags: ['Sleep', 'Melatonin'],
      },
      {
        id:'4',
        name: 'Aquilea Sueno Gummies',
        price: 2,
        dosage: '3-4',
        favorite: true,
        origins: 'Uriach',
        stars: 3.3,
        imageUrl: 'assets/4.jpg',
        tags: ['Sleep', 'Melatonin','Calm','Relax'],
      },
      {
        id:'5',
        name: 'Cholesfytol',
        price: 11,
        dosage: '4-5',
        favorite: false,
        origins: 'Tilman',
        stars: 3.0,
        imageUrl: 'assets/5.jpg',
        tags: ['Cholesterol', 'Heart'],
      },
      {
        id:'6',
        name: 'Colpofix',
        price: 9,
        dosage: '4-5',
        favorite: false,
        origins: 'Uriach',
        stars: 4.0,
        imageUrl: 'assets/6.jpg',
        tags: ['Hpv', 'Uterus'],
      },
]